district <- read.csv('/home/glenn/oss/hadoop/hadoop-1.0.4/bydistrict/part-00000', header = FALSE)
pr <- range(0, district$V2, district$V3, district$V4, district$V5, district$V6, district$V7, district$V8, district$V9, district$V10, district$V11, district$V12, district$V13, district$V14, district$V15, district$V16, district$V17)
mission <- t(district[district$V1 == "MISSION",])
southern <- t(district[district$V1 == "SOUTHERN",])
tenderloin <- t(district[district$V1 == "TENDERLOIN",])
richmond <- t(district[district$V1 == "RICHMOND",])
plot(mission, type="o", col="red", ylim=pr, xlim=c(-4, 12), axes=FALSE, ann=FALSE)
lines(southern, type="o", col="green")
lines(tenderloin, type="o", col="blue")
lines(richmond, type="o", col="orange")
legend(-4, max(pr), c("mission", "southern", "tenderloin", "richmond"), col=c("red", "green", "blue", "orange"), cex=0.8, lty=1:2)
title(main="San Francisco Crime Date", sub="Q1 2013", xlab="week", ylab="crimes")
